### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by tetebueno** [FossifyOrg/Draw#11]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Draw/issues) or [closed](https://github.com/FossifyOrg/Draw/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Draw/discussions) or [closed](https://github.com/FossifyOrg/Draw/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Draw/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Like other Fossify apps, it'd be great to be able to install the app via F-Droid.

### Why do you want this feature?

Fue to all the benefits an app manager such as F-Droid provides.

### Additional information

I'm sure is in the roadmap, but I report it just to track it.

**Comment by Aga-C** [comment]
You can track, what and where has been released, here: https://github.com/orgs/FossifyOrg/discussions/9#discussioncomment-8094221.

**Comment by maverick74** [comment]
This is kind of a "me too"! 

I use this a lot and I am also waiting for its release! 🙂 thanks

**Comment by maverick74** [comment]
Thank you for the release @naveensingh (and happy new year to everyone)

**Comment by naveensingh** [comment]
_Happy New Year!_
